//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PBO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_resize_ {
            get {
                object obj = ResourceManager.GetObject("bg(resize)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDUKASI_ALGORITMA_DAN_PEMROGRAMAN {
            get {
                object obj = ResourceManager.GetObject("EDUKASI-ALGORITMA DAN PEMROGRAMAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDUKASI_ARSITEKTUR_DAN_ORGANISASI_KOMPUTER {
            get {
                object obj = ResourceManager.GetObject("EDUKASI-ARSITEKTUR DAN ORGANISASI KOMPUTER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDUKASI_BIOKIMIA_1 {
            get {
                object obj = ResourceManager.GetObject("EDUKASI-BIOKIMIA 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDUKASI_DASAR_DASAR_EKONOMI {
            get {
                object obj = ResourceManager.GetObject("EDUKASI-DASAR-DASAR EKONOMI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDUKASI_FISIKA_DASAR_1 {
            get {
                object obj = ResourceManager.GetObject("EDUKASI-FISIKA DASAR 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDUKASI_KIMIA_DASAR_1 {
            get {
                object obj = ResourceManager.GetObject("EDUKASI-KIMIA DASAR 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDUKASI_MANAJEMEN_KEUANGAN {
            get {
                object obj = ResourceManager.GetObject("EDUKASI-MANAJEMEN KEUANGAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDUKASI_MATEMATIKA_DISKRIT {
            get {
                object obj = ResourceManager.GetObject("EDUKASI-MATEMATIKA DISKRIT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDUKASI_PEMROGRAMAN_BERORIENTASI_OBJEK_C3 {
            get {
                object obj = ResourceManager.GetObject("EDUKASI-PEMROGRAMAN BERORIENTASI OBJEK C3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDUKASI_TEORI_KESUSASTRAAN {
            get {
                object obj = ResourceManager.GetObject("EDUKASI-TEORI KESUSASTRAAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ENSIKLOPEDIA__MITOLOGI_YUNANI_ {
            get {
                object obj = ResourceManager.GetObject("ENSIKLOPEDIA- MITOLOGI YUNANI ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ENSIKLOPEDIA_ANATOMI_TUBUH_MANUSIA {
            get {
                object obj = ResourceManager.GetObject("ENSIKLOPEDIA-ANATOMI TUBUH MANUSIA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ENSIKLOPEDIA_ASTRONOMI {
            get {
                object obj = ResourceManager.GetObject("ENSIKLOPEDIA-ASTRONOMI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ENSIKLOPEDIA_BERGAMBAR_SEJARAH_DUNIA {
            get {
                object obj = ResourceManager.GetObject("ENSIKLOPEDIA-BERGAMBAR SEJARAH DUNIA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ENSIKLOPEDIA_ILMU_PENGETAHUAN_MODERN {
            get {
                object obj = ResourceManager.GetObject("ENSIKLOPEDIA-ILMU PENGETAHUAN MODERN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ENSIKLOPEDIA_PENDIDIKAN_DAN_PSIKOLOGI {
            get {
                object obj = ResourceManager.GetObject("ENSIKLOPEDIA-PENDIDIKAN DAN PSIKOLOGI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ENSIKLOPEDIA_PSIKOLOGI {
            get {
                object obj = ResourceManager.GetObject("ENSIKLOPEDIA-PSIKOLOGI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ENSIKLOPEDIA_SEJARAH_NASIONAL_DAN_DUNIA {
            get {
                object obj = ResourceManager.GetObject("ENSIKLOPEDIA-SEJARAH NASIONAL DAN DUNIA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ENSIKLOPEDIA_SUKU_SENI_DAN_BUDAYA_NASIONAL {
            get {
                object obj = ResourceManager.GetObject("ENSIKLOPEDIA-SUKU,SENI DAN BUDAYA NASIONAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ENSIKLOPEDIFINALOKE {
            get {
                object obj = ResourceManager.GetObject("ENSIKLOPEDIFINALOKE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gabyy {
            get {
                object obj = ResourceManager.GetObject("Gabyy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iginiii {
            get {
                object obj = ResourceManager.GetObject("iginiii", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_20230117_WA0000 {
            get {
                object obj = ResourceManager.GetObject("IMG-20230117-WA0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KOMIK_BLUE_LOCK {
            get {
                object obj = ResourceManager.GetObject("KOMIK-BLUE LOCK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KOMIK_DEATH_NOTE {
            get {
                object obj = ResourceManager.GetObject("KOMIK-DEATH NOTE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KOMIK_DETEKTIF_CONAN {
            get {
                object obj = ResourceManager.GetObject("KOMIK-DETEKTIF CONAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KOMIK_DRAGON_BALL {
            get {
                object obj = ResourceManager.GetObject("KOMIK-DRAGON BALL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KOMIK_HAIKYU {
            get {
                object obj = ResourceManager.GetObject("KOMIK-HAIKYU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KOMIK_IDOL_PRETENDER {
            get {
                object obj = ResourceManager.GetObject("KOMIK-IDOL PRETENDER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KOMIK_NARUTO {
            get {
                object obj = ResourceManager.GetObject("KOMIK-NARUTO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KOMIK_ONE_PIECE {
            get {
                object obj = ResourceManager.GetObject("KOMIK-ONE PIECE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KOMIK_THEIR_STORY {
            get {
                object obj = ResourceManager.GetObject("KOMIK-THEIR STORY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KOMIK_TOKYO_REVENGERS {
            get {
                object obj = ResourceManager.GetObject("KOMIK-TOKYO REVENGERS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap teriaa {
            get {
                object obj = ResourceManager.GetObject("teriaa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap triaa {
            get {
                object obj = ResourceManager.GetObject("triaa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
